/*
 * KubernetesAccessManager - API
 *
 * This is a backend API server documentation for KubernetesAccessManager  Some useful links: - [Jira](https://samuelus.atlassian.net/jira/software/projects/ZPI/boards/4) - [Confluence](https://samuelus.atlassian.net/wiki/spaces/ZPI/overview)
 *
 * API version: 0.0.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package api

import (
	"github.com/ZPI-2024-25/KubernetesAccessManager/controllers"
	"net/http"
)

func GetHelmRelease(w http.ResponseWriter, r *http.Request) {
	controllers.GetHelmReleaseController(w, r)
}

func GetHelmReleaseHistory(w http.ResponseWriter, r *http.Request) {
	controllers.GetHelmReleaseHistoryController(w, r)
}

func ListHelmReleases(w http.ResponseWriter, r *http.Request) {
	controllers.ListHelmReleasesController(w, r)
}

func RollbackHelmRelease(w http.ResponseWriter, r *http.Request) {
	controllers.RollbackHelmReleaseController(w, r)
}

func UninstallHelmRelease(w http.ResponseWriter, r *http.Request) {
	controllers.UninstallHelmReleaseController(w, r)
}
