/*
 * KubernetesAccessManager - API
 *
 * This is a backend API server documentation for KubernetesAccessManager  Some useful links: - [Jira](https://samuelus.atlassian.net/jira/software/projects/ZPI/boards/4) - [Confluence](https://samuelus.atlassian.net/wiki/spaces/ZPI/overview)
 *
 * API version: 0.0.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package api

import (
	"net/http"

	"github.com/ZPI-2024-25/KubernetesAccessManager/controllers"
)

func CheckLoginStatus(w http.ResponseWriter, r *http.Request) {
	controllers.CheckLoginStatus(w, r)
}
