/*
 * KubernetesAccessManager - API
 *
 * This is a backend API server documentation for KubernetesAccessManager  Some useful links: - [Jira](https://samuelus.atlassian.net/jira/software/projects/ZPI/boards/4) - [Confluence](https://samuelus.atlassian.net/wiki/spaces/ZPI/overview)
 *
 * API version: 0.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package api

import (
	"github.com/ZPI-2024-25/KubernetesAccessManager/controllers"
	"net/http"
)

func CreateResource(w http.ResponseWriter, r *http.Request) {
	controllers.CreateResourceController(w, r)
}

func DeleteResource(w http.ResponseWriter, r *http.Request) {
	controllers.DeleteClusterResourceController(w, r)
}

func GetResource(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
}

func ListResources(w http.ResponseWriter, r *http.Request) {
	controllers.ListResourcesController(w, r)
}

func UpdateResource(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
}
