apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "charts.fullnameFrontend" . }}
  labels:
    {{- include "charts.labelsFrontend" . | nindent 4 }}
spec:
  {{- if not .Values.frontend.autoscaling.enabled }}
  replicas: {{ .Values.frontend.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "charts.selectorLabelsFrontend" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "charts.labelsFrontend" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "charts.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}-frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag | default (printf "v%s" .Chart.AppVersion) }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.service.port }}
              protocol: TCP
          env:
            - name: BACKEND_SERVICE_HOST
              value: {{ include "charts.fullnameBackend" . }}
            - name: BACKEND_SERVICE_PORT
              value: {{ .Values.backend.service.port | quote }}