apiVersion: v1
kind: Service
metadata:
  name: {{ include "charts.fullnameFrontend" . }}
  labels:
    {{- include "charts.labelsFrontend" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "charts.selectorLabelsFrontend" . | nindent 4 }}
