# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-permissions-db
spec:
  selector:
    matchLabels:
      app: users-permissions-db
  replicas: 1
  template:
    metadata:
      labels:
        app: users-permissions-db
    spec:
      containers:
        - name: users-permissions-db
          image: postgres:17
          ports:
            - containerPort: 5432
              name: "postgres"
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: users-permissions-postgres-data-storage
          env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: db-password
                  key: password
          resources:
            limits:
              memory: 4Gi
              cpu: "2"
      volumes:
        - name: users-permissions-postgres-data-storage
          persistentVolumeClaim:
            claimName: users-permissions-postgres-data-persistent-volume-claim  