{{- if .Values.backend.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "charts.fullname" . }}
  labels:
    {{- include "charts.labelsBackend" . | nindent 4 }}
rules:
{{ toYaml .Values.backend.rbac.rules | indent 2 }}
{{- end }}

