{{- if .Values.backend.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "charts.fullname" . }}
  labels:
    {{- include "charts.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "charts.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "charts.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
