apiVersion: v1
kind: Service
metadata:
  name: {{ include "charts.fullnameBackend" . }}
  labels:
    {{- include "charts.labelsBackend" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "charts.selectorLabelsBackend" . | nindent 4 }}
