apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "charts.fullnameBackend" . }}
  labels:
    {{- include "charts.labelsBackend" . | nindent 4 }}
spec:
  {{- if not .Values.backend.autoscaling.enabled }}
  replicas: {{ .Values.backend.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "charts.selectorLabelsBackend" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "charts.labelsBackend" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "charts.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}-backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag | default (printf "v%s" .Chart.AppVersion) }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.backend.service.port }}
              protocol: TCP
          env:
            - name: VITE_KEYCLOAK_URL
              value: "{{ .Values.KEYCLOAK_URL }}"
            - name: VITE_KEYCLOAK_CLIENTNAME
              value: "{{ .Values.KEYCLOAK_CLIENTNAME }}"
            - name: VITE_KEYCLOAK_REALMNAME
              value: "{{ .Values.KEYCLOAK_REALMNAME }}"
            - name: VITE_ROLEMAP_NAMESPACE
              value: "{{ .Values.ROLEMAP_NAMESPACE }}"
            - name: VITE_ROLEMAP_NAME
              value: "{{ .Values.ROLEMAP_NAME }}"
          livenessProbe:
            {{- toYaml .Values.backend.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.backend.readinessProbe | nindent 12 }}
