/*
 * KubernetesAccessManager - API
 *
 * This is a backend API server documentation for KubernetesAccessManager  Some useful links: - [Jira](https://samuelus.atlassian.net/jira/software/projects/ZPI/boards/4) - [Confluence](https://samuelus.atlassian.net/wiki/spaces/ZPI/overview)
 *
 * API version: 0.0.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type UserStatusUser struct {
	// JWT expiration time
	Exp int32 `json:"exp,omitempty"`
	// User's preferred username
	PreferredUsername string `json:"preferred_username,omitempty"`
	// User's email address
	Email string `json:"email,omitempty"`
}
