/*
 * KubernetesAccessManager - API
 *
 * This is a backend API server documentation for KubernetesAccessManager  Some useful links: - [Jira](https://samuelus.atlassian.net/jira/software/projects/ZPI/boards/4) - [Confluence](https://samuelus.atlassian.net/wiki/spaces/ZPI/overview)
 *
 * API version: 0.0.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ResourceListResourceList struct {
	// Optional value for 'active'
	Active string `json:"active,omitempty"`
	// Optional value for 'age'
	Age string `json:"age,omitempty"`
	// Optional value for 'bindings'
	Bindings string `json:"bindings,omitempty"`
	// Optional value for 'capacity'
	Capacity string `json:"capacity,omitempty"`
	// Optional value for 'claim'
	Claim string `json:"claim,omitempty"`
	// Optional value for 'cluster_ip'
	ClusterIp string `json:"cluster_ip,omitempty"`
	// Optional value for 'completions'
	Completions string `json:"completions,omitempty"`
	// Optional value for 'conditions'
	Conditions string `json:"conditions,omitempty"`
	// Optional value for 'containers'
	Containers string `json:"containers,omitempty"`
	// Optional value for 'controlled_by'
	ControlledBy string `json:"controlled_by,omitempty"`
	// Optional value for 'current'
	Current string `json:"current,omitempty"`
	// Optional value for 'default'
	Default_ string `json:"default,omitempty"`
	// Optional value for 'desired'
	Desired string `json:"desired,omitempty"`
	// Optional value for 'external_ip'
	ExternalIp string `json:"external_ip,omitempty"`
	// Optional value for 'group'
	Group string `json:"group,omitempty"`
	// Optional value for 'keys'
	Keys string `json:"keys,omitempty"`
	// Optional value for 'labels'
	Labels string `json:"labels,omitempty"`
	// Optional value for 'last_schedule'
	LastSchedule string `json:"last_schedule,omitempty"`
	// Optional value for 'loadbalancers'
	Loadbalancers string `json:"loadbalancers,omitempty"`
	// Optional value for 'name'
	Name string `json:"name,omitempty"`
	// Optional value for 'namespace'
	Namespace string `json:"namespace,omitempty"`
	// Optional value for 'node'
	Node string `json:"node,omitempty"`
	// Optional value for 'node_selector'
	NodeSelector string `json:"node_selector,omitempty"`
	// Optional value for 'pods'
	Pods string `json:"pods,omitempty"`
	// Optional value for 'ports'
	Ports string `json:"ports,omitempty"`
	// Optional value for 'provisioner'
	Provisioner string `json:"provisioner,omitempty"`
	// Optional value for 'qos'
	Qos string `json:"qos,omitempty"`
	// Optional value for 'ready'
	Ready string `json:"ready,omitempty"`
	// Optional value for 'reclaim_policy'
	ReclaimPolicy string `json:"reclaim_policy,omitempty"`
	// Optional value for 'replicas'
	Replicas string `json:"replicas,omitempty"`
	// Optional value for 'resource'
	Resource string `json:"resource,omitempty"`
	// Optional value for 'restarts'
	Restarts string `json:"restarts,omitempty"`
	// Optional value for 'roles'
	Roles string `json:"roles,omitempty"`
	// Optional value for 'rules'
	Rules string `json:"rules,omitempty"`
	// Optional value for 'schedule'
	Schedule string `json:"schedule,omitempty"`
	// Optional value for 'scope'
	Scope string `json:"scope,omitempty"`
	// Optional value for 'selector'
	Selector string `json:"selector,omitempty"`
	// Optional value for 'size'
	Size string `json:"size,omitempty"`
	// Optional value for 'status'
	Status string `json:"status,omitempty"`
	// Optional value for 'storage_class'
	StorageClass string `json:"storage_class,omitempty"`
	// Optional value for 'suspend'
	Suspend string `json:"suspend,omitempty"`
	// Optional value for 'taints'
	Taints string `json:"taints,omitempty"`
	// Optional value for 'type'
	Type_ string `json:"type,omitempty"`
	// Optional value for 'version'
	Version string `json:"version,omitempty"`
}
