/*
 * KubernetesAccessManager - API
 *
 * This is a backend API server documentation for KubernetesAccessManager  Some useful links: - [Jira](https://samuelus.atlassian.net/jira/software/projects/ZPI/boards/4) - [Confluence](https://samuelus.atlassian.net/wiki/spaces/ZPI/overview)
 *
 * API version: 0.0.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

// Permissions matrix where rows are resources, columns are namespaces, and values are lists of allowed operations.
type UserStatusPermissions struct {
	// List of resources corresponding to rows in the matrix.
	Resources []string `json:"resources,omitempty"`
	// List of namespaces corresponding to columns in the matrix.
	Namespaces []string `json:"namespaces,omitempty"`
	// Matrix of permissions where each row corresponds to a resource and each column corresponds to a namespace.
	Matrix [][][]string `json:"matrix,omitempty"`
}
