apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-go-test
  labels:
    app: client-go-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: client-go-test
  template:
    metadata:
      labels:
        app: client-go-test
    spec:
      containers:
      - name: app
        image: client-go-test:v1
        ports:
        - containerPort: 8080