apiVersion: apps/v1
kind: Deployment
metadata:
  name: kam-backend
  labels:
    app: kam-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kam-backend
  template:
    metadata:
      labels:
        app: kam-backend
    spec:
      containers:
      - name: app
        image: ninjashadow/kubernetes-access-manager-backend:v1.0.0
        ports:
        - containerPort: 8080