apiVersion: v1
kind: Service
metadata:
  name: client-go-test-svc
spec:
  type: LoadBalancer
  selector:
    app: client-go-test
  ports:
  - name: client-go-test-port
    protocol: TCP
    port: 8080
    targetPort: 8080