apiVersion: v1
kind: Service
metadata:
  name: kam-backend-svc
spec:
  type: LoadBalancer
  selector:
    app: kam-backend
  ports:
  - name: kam-backend-port
    protocol: TCP
    port: 8080
    targetPort: 8080