apiVersion: v1
kind: PersistentVolume
metadata:
  name: users-permissions-postgres-data-persistent-volume
  labels:
    type: local
spec:
  claimRef:
    namespace: default
    name: users-permissions-postgres-data-persistent-volume-claim
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"