apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: users-permissions-postgres-data-persistent-volume-claim
spec:
  volumeName: users-permissions-postgres-data-persistent-volume
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi