apiVersion: v1
kind: ConfigMap
metadata:
  name: role-mapper
  namespace: default
data:
  role-map: |
    superadmin:
      deny: 
        - resource: "Pod"
          type: "*"
          namespace: "*"
      permit:
        - resource: "*"
          type: "*"
          namespace: "*"
      subroles:
        - "admin"
    user:
      permit:
        - resource: "Pod"
          type: "read"
          namespace: "default"
      subroles:
        - "guest"
    guest:
      permit:
        - resource: "Pod"
          type: "list"
          namespace: "default"

  subrole-map: |
    admin:
      deny: 
        - resource: "Pod"
          type: "*"
          namespace: "*"
      permit:
        - resource: "*"
          type: "*"
          namespace: "*"
      subroles:
        - "admin"
    pod-viewer:
      permit:
        - resource: "Pod"
          type: "read"
          namespace: "*"
        - resource: "Pod"
          type: "list"
          namespace: "*"
