apiVersion: v1
kind: ConfigMap
metadata:
  name: role-mapper
  namespace: default
data:
  role-map: |
    admin:
      name: "admin"
      deny: 
        - resource: "Pod"
          namespace: "default"
          operations: ["delete", "create"]
      permit:
        - resource: "*"
          namespace: "*"
          operations: ["*"]
        - resource: "Pod"
          namespace: "default"
          operations: ["list", "read"]
      subroles:
        - "user"
    user:
      name: "user"
      permit:
        - resource: "Pod"
          operations: ["read"]
          namespace: "default"
      subroles:
        - "guest"
    guest:
      name: "guest"
      permit:
        - resource: "Pod"
          operations: ["list"]
          namespace: "default"
  subrole-map: |
    superadmin:
      name: "superadmin"
      permit:
        - resource: "*"
          operations: ["*"]
          namespace: "*"
      subroles:
        - "admin"
    viewer:
      name: "viewer"
      permit:
        - resource: "Pod"
          operations: ["read"]
