name: Build and Push Docker Images

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Dockerfile1'
      - 'Dockerfile2'
      - 'backend/**'
      - 'frontend/**'
      - 'charts/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'Dockerfile1'
      - 'Dockerfile2'
      - 'backend/**'
      - 'frontend/**'
      - 'charts/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/download/v4.35.1/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      - name: Extract appVersion from Chart.yaml
        id: extract_app_version
        run: |
          APP_VERSION=$(yq e '.appVersion' charts/kam/Chart.yaml)
          echo "App version: $APP_VERSION"
          echo "::set-output name=app_version::$APP_VERSION"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push backend image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile1
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ steps.extract_app_version.outputs.app_version }}
            ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest

      - name: Build and push frontend image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile2
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/frontend:${{ steps.extract_app_version.outputs.app_version }}
            ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest

      - name: Log out from Docker Hub
        run: docker logout
