name: Build and Push Docker Images

on:
  push:
    branches: [ "main" ]
    paths:
      - 'charts/kam/Chart.yaml'
  workflow_dispatch:

jobs:
  validate-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: '2'

      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/download/v4.35.1/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      - name: Check if appVersion changed
        id: check_version
        run: |
          CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD)

          CURRENT_VERSION=$(yq e '.appVersion' charts/kam/Chart.yaml)
          PREVIOUS_VERSION=$(git show HEAD~1:charts/kam/Chart.yaml | yq e '.appVersion' -)
          echo "Current appVersion: $CURRENT_VERSION"
          echo "Previous appVersion: $PREVIOUS_VERSION"
          
          if [[ ! "$CURRENT_VERSION" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Error: appVersion must be in the format v<major>.<minor>.<patch>, e.g. v1.0.0"
            exit 1
          fi

          if [ "$CURRENT_VERSION" == "$PREVIOUS_VERSION" ]; then
            echo "::set-output name=version_changed::false"
            echo "appVersion has not changed. Skipping the rest of the pipeline."
            exit 0
          else
            echo "::set-output name=version_changed::true"
            echo "appVersion has changed. Proceeding with the build."
          fi

      - name: Log in to Docker Hub
        if: steps.check_version.outputs.version_changed == 'true'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        if: steps.check_version.outputs.version_changed == 'true'
        uses: docker/setup-buildx-action@v2

      - name: Build and push backend image
        if: steps.check_version.outputs.version_changed == 'true'
        uses: docker/build-push-action@v4
        with:
          context: backend
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ steps.extract_app_version.outputs.app_version }}
            ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest

      - name: Build and push frontend image
        if: steps.check_version.outputs.version_changed == 'true'
        uses: docker/build-push-action@v4
        with:
          context: frontend
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/frontend:${{ steps.extract_app_version.outputs.app_version }}
            ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest

      - name: Log out from Docker Hub
        if: steps.check_version.outputs.version_changed == 'true'
        run: docker logout
