name: Go

on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/**.go'
      - 'backend/go.mod'
      - 'backend/go.sum'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'backend/**.go'
      - 'backend/go.mod'
      - 'backend/go.sum'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.5

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('backend/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        working-directory: backend
        run: go mod download

      - name: Build
        working-directory: backend
        run: go build -v ./...

      - name: Run tests
        working-directory: backend
        run: go test -v ./...

      - name: Run linters
        working-directory: backend
        run: |
          go install golang.org/x/lint/golint@latest
          golint ./...
